Threshold = 90
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_SUGA_2020_08_27_99508-00.mono-fallback"
LastUsedOutput = ""
