#!/usr/bin/env bash

FILEPATH="$(xdg-user-dir PICTURES)/screenshots"
FILENAME=screenshot_$(date +"%y-%m-%d_%H-%M-%S").png

if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
    /usr/bin/grimblast check
    ENTRIES="Active Screen Output Area"
elif [[ "$XDG_CURRENT_DESKTOP" == "sway" ]]; then
    /usr/share/sway-contrib/grimshot check
    ENTRIES="Active Screen Output Area Window Anything"
else
    exit 0
fi

LINE_COUNT=$(echo "${ENTRIES}" | tr -d -c ' ' | wc -m)
((LINE_COUNT++))

if [ -n "$1" ]; then
    SELECTED="$1"
else
    SELECTED=$(echo "${ENTRIES}" | tr ' ' '\n' | fuzzel -d -a top-right -l "${LINE_COUNT}" -w 14 | awk '{print tolower($1)}')
fi

if [ -z "$SELECTED" ]; then
    exit 0
fi

if [ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]; then
    /usr/bin/grimblast copysave "${SELECTED}" "${FILEPATH}/${FILENAME//screenshot/${SELECTED}}"
elif [ "$XDG_CURRENT_DESKTOP" == "sway" ]; then
    /usr/share/sway-contrib/grimshot --cursor savecopy "${SELECTED}" "${FILEPATH}/${FILENAME//screenshot/${SELECTED}}"
else
    exit 0
fi
